"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000

# Prompt layout
format = """
($package\
$c\
$rust\
$golang\
$nodejs\
$bun\
$java\
$maven\
$python\
\n)\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$fill\
$line_break\
$character"""

palette = 'default'

[fill]
symbol = " "

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[directory]
style = "blue"
format = "[$path]($style)"
truncation_length = 3

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bright_black"
format = '[ on $symbol $branch]($style)'

[git_state]
format = '[ \($state( $progress_current/$progress_total)\)]($style)'
cherry_pick = 'CHERRY PICKING'
style = "pink"

[git_status]
format = "[ [($conflicted$untracked$modified$staged$renamed$deleted$stashed)](pink)($ahead_behind)]($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = ""
ahead = "${count}"
behind = "${count}"
diverged = "${ahead_count}${behind_count}"

[package]
symbol = "󰏗"
style = "fg:package_fg bg:package_bg"
format = '[](fg:package_bg)[$symbol( $version)]($style)[](fg:package_bg) '

[nodejs]
symbol = ""
style = "fg:nodejs_fg bg:nodejs_bg"
format = '[](fg:nodejs_bg)[$symbol( $version)]($style)[](fg:nodejs_bg) '

[bun]
symbol = ""
style = "fg:bun_fg bg:bun_bg"
format = '[](fg:bun_bg)[$symbol( $version)]($style)[](fg:bun_bg) '

[c]
symbol = ""
style = "fg:c_fg bg:c_bg"
format = '[](fg:c_bg)[$symbol( $version)]($style)[](fg:c_bg) '

[rust]
symbol = ""
style = "fg:rust_fg bg:rust_bg"
format = '[](fg:rust_bg)[$symbol( $version)]($style)[](fg:rust_bg) '

[golang]
symbol = ""
style = "fg:golang_fg bg:golang_bg"
format = '[](fg:golang_bg)[$symbol( $version)]($style)[](fg:golang_bg) '

[java]
symbol = ""
style = "fg:java_fg bg:java_bg"
format = '[](fg:java_bg)[$symbol( $version)]($style)[](fg:java_bg) '

[maven]
symbol = ""
style = "fg:maven_fg bg:maven_bg"
format = '[](fg:maven_bg)[$symbol( $version)]($style)[](fg:maven_bg) '

[kotlin]
symbol = ""
style = "fg:kotlin_fg bg:kotlin_bg"
format = '[](fg:kotlin_bg)[$symbol( $version)]($style)[](fg:kotlin_bg) '

[python]
symbol = ""
style = "fg:python_fg bg:python_bg"
format = '[](fg:python_bg)[ $symbol( $version)(\(#$virtualenv\))]($style)[](fg:python_bg) '

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'
vimcmd_replace_one_symbol = '[❮](bold lavender)'
vimcmd_replace_symbol = '[❮](bold lavender)'
vimcmd_visual_symbol = '[❮](bold yellow)'

[cmd_duration]
style = "yellow"
format = '[  $duration]($style) '
min_time = 2_000

[palettes.default]
red = "#ed8796"
yellow = "#eed49f"
green = "#a6da95"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
crust = "#181926"
bright_black = "#808080"
pink = "#ffafd7"

# Language/tool module colors
package_fg = "#26272A"
package_bg = "#D0DBDA"
nodejs_fg = "#84ba64"
nodejs_bg = "#333333"
bun_fg = "#26272A"
bun_bg = "#F1DEA9"
c_fg = "#EDF2F4"
c_bg = "#00599D"
rust_fg = "#EDF2F4"
rust_bg = "#C33C00"
golang_fg = "#26272A"
golang_bg = "#7FD5EA"
java_fg = "#ffffff"
java_bg = "#cc7700"
maven_fg = "#EDF2F4"
maven_bg = "#861215"
kotlin_fg = "#EDF2F4"
kotlin_bg = "#7F52FF"
python_fg = "#26272A"
python_bg = "#F5CB5C"
